[[custom_groups]]
name = "🔰 节点选择"
type = "select"
rule = ["[]♻️ 自动选择", "[]🎯 全球直连", "[]强制选择", "[]🇲🇴 Macau", "[]Haruka", "[]🇹🇼 Taiwan", "[]🇭🇰 Hong Kong", "[]🇯🇵 Japan", "[]🇰🇷 South Korea", "[]🇸🇬 Singapore"]

[[custom_groups]]
name = "强制选择"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "Haruka"
type = "select"
rule = ["(Haruka)"]

[[custom_groups]]
name = "osu!"
type = "select"
rule = ["[]🔰 节点选择", "[]强制选择", "[]🎯 全球直连", "[]🇲🇴 Macau", "[]Haruka"]

[[custom_groups]]
name = "Discord"
type = "select"
rule = ["[]🔰 节点选择", "[]强制选择", "[]🎯 全球直连", "[]🇭🇰 Hong Kong", "[]🇯🇵 Japan", "[]🇸🇬 Singapore"]

[[custom_groups]]
name = "DMM Games"
type = "select"
rule = ["[]🇯🇵 Japan", "(JP|Japan|日本|东京|大阪|埼玉|[^-]日)"]

[[custom_groups]]
name = "Tarkov"
type = "select"
rule = ["(RU|Russia|俄罗斯|莫斯科|圣彼得堡)"]

[[custom_groups]]
name = "Temporary"
type = "select"
rule = ["[]🔰 节点选择", "[]强制选择", "[]🎯 全球直连"]

[[custom_groups]]
name = "Bilibili"
type = "select"
rule = ["[]🔰 节点选择", "[]强制选择", "[]🎯 全球直连", "[]🇲🇴 Macau", "[]Haruka"]

[[custom_groups]]
name = "🇲🇴 Macau"
type = "url-test"
rule = ["(MO|MAC|Macau|Macao|澳门|CTM|MTel|澳門)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "🇭🇰 Hong Kong"
type = "url-test"
rule = ["(?i:HK|Hong.*?Kong|HKT|HKBN|HGC|WTT|CMI|[^-]港)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "🇹🇼 Taiwan"
type = "url-test"
rule = ["(Taiwan|TW|TWN|新北|彰化|CHT|台湾|[^-]台|HINET)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "🇯🇵 Japan"
type = "url-test"
rule = ["(JP|Japan|日本|东京|大阪|埼玉|[^-]日)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "🇰🇷 South Korea"
type = "url-test"
rule = ["(?i:KR|Korea|KOR|首尔|韩|韓)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "🇸🇬 Singapore"
type = "url-test"
rule = ["(?i:SG|Singapore|新加坡|狮城)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "🎥 NETFLIX"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]♻️ 自动选择",
    "[]🎯 全球直连",
    ".*"
]

[[custom_groups]]
name = "⛔️ 广告拦截"
type = "select"
rule = ["[]🛑 全球拦截",
"[]🎯 全球直连",
"[]🔰 节点选择"
]

[[custom_groups]]
name = "🚫 运营劫持"
type = "select"
rule = ["[]🛑 全球拦截",
"[]🎯 全球直连",
"[]🔰 节点选择"]

[[custom_groups]]
name = "🌍 国外媒体"
type = "select"
rule = ["[]🔰 节点选择",
"[]♻️ 自动选择",
"[]🎯 全球直连",
".*"]

[[custom_groups]]
name = "🌏 国内媒体"
type = "select"
rule = ["[]🎯 全球直连", "[]🇲🇴 Macau", "[]🇹🇼 Taiwan", "[]🇭🇰 Hong Kong", "[]Haruka"]

[[custom_groups]]
name = "Ⓜ️ 微软服务"
type = "select"
rule = ["[]🎯 全球直连",
"[]🔰 节点选择",
".*"]

[[custom_groups]]
name = "📲 电报信息"
type = "select"
rule = ["[]🔰 节点选择",
"[]🎯 全球直连",
".*"]

[[custom_groups]]
name = "🍎 苹果服务"
type = "select"
rule = ["[]🔰 节点选择",
"[]🎯 全球直连",
"[]♻️ 自动选择",
".*"]

[[custom_groups]]
name = "🎯 全球直连"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "🛑 全球拦截"
type = "select"
rule = ["[]REJECT", "[]DIRECT"]

[[custom_groups]]
name = "🐟 漏网之鱼"
type = "select"
rule = ["[]🔰 节点选择",
"[]🎯 全球直连",
"[]♻️ 自动选择",
".*"]

[[custom_groups]]
name = "♻️ 自动选择"
type = "url-test"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 300